### ISSUE TITLE
Issues with re-running the java version of the client

### ISSUE THREAD

**Issue by neomatrix369** [wandb/client-java#2]
After cloning this project, and running the steps as mentioned in the README. I can the generated uber jar. It runs and sends metrics to my project the first time when I run:
```
$ java -jar target/client-ng-java-1.0-SNAPSHOT-jar-with-dependencies.jar
```
but then it fails to shutdown the `grpc` server -- hangs for a long time.

Rerunning the jar results in hanging/pausing.

Workaround:

```
$ kill -9 $(ps aux | grep grpc | awk '{print $2}')
```
followed by

```
$ wandb grpc-server
```

And then re-running the `jar` works fine.

**Comment by neomatrix369** [comment]
One instance of execution gave this exception:

```
 java -jar target/client-ng-java-1.0-SNAPSHOT-jar-with-dependencies.jar
Hello from wandb in java using GRPC!
Creating Runner
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda3/lib/python3.7/site-packages/grpc/_server.py", line 875, in _serve
    if not _process_event_and_continue(state, event):
  File "/anaconda3/lib/python3.7/site-packages/grpc/_server.py", line 842, in _process_event_and_continue
    concurrency_exceeded)
  File "/anaconda3/lib/python3.7/site-packages/grpc/_server.py", line 750, in _handle_call
    thread_pool)
  File "/anaconda3/lib/python3.7/site-packages/grpc/_server.py", line 726, in _handle_with_method_handler
    method_handler, thread_pool)
  File "/anaconda3/lib/python3.7/site-packages/grpc/_server.py", line 632, in _handle_unary_unary
    method_handler.response_serializer)
  File "/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 153, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

**Comment by neomatrix369** [comment]
Would this PR https://github.com/wandb/client-java/pull/1  be able to help with this issue?

**Comment by raubitsj** [comment]
We only support a single wandb run with the java client right now.  
If you make sure there is no grpc-server running and launch the jar file, it will launch the grpcserver and it will shut it down.

I am leaving this open until we fix the single grpc-server issue, there is no reason for it as we can run them at different ports.

Eventually we will be able to run multiple java clients in parallel using the same grpc-server but that is farther out.

**Comment by raubitsj** [comment]
There are cases where if the java code crashes, the grpc-server might remain running.  That is a bug and will be fixed when we allow multiple java clients to run in parallel (on different ports)
